config:
    packages:
        -
            name: 'ekyna-cms'
            location: 'bundles/ekynacms/js'
            main: 'cms'
    paths:
        'ekyna-cms/slide-types':
            route: ekyna_cms_slide_types
            params: []
build:
    include:
        - 'ekyna-cms/cms'
    paths:
        'ekyna-cms/slide-types': 'empty:'
