config:
    shim:
        backbone:
            deps: ['underscore']
            exports: 'Backbone'
        underscore:
            exports: '_'
        'ekyna-cms/editor':
            deps: ['routing']
#    packages: TODO
#        -
#            name: 'ekyna-cms/editor'
#            location: 'bundles/ekynacms/js/editor'
#            main: 'editor'
    paths:
        'ekyna-cms/editor': 'bundles/ekynacms/js/editor'
#        'ekyna-cms-editor/plugin-base': 'bundles/ekynacms/js/editor/plugin/base'
#        'ekyna-cms-editor/tinymce': 'bundles/ekynacms/js/editor/plugin/tinymce'
#        'ekyna-cms-editor/image': 'bundles/ekynacms/js/editor/plugin/image'
        'ekyna-cms/cookie': 'bundles/ekynacms/js/cookie'
        'ekyna-cms/user': 'bundles/ekynacms/js/user'
        backbone: 'bundles/ekynacms/lib/backbone'
        underscore: 'bundles/ekynacms/lib/underscore'
build:
    include:
#        - 'ekyna-cms-editor'
#        - 'ekyna-cms-editor/plugin-base'
        - 'ekyna-cms/cookie'
        - 'ekyna-cms/user'
#    paths:
#        'routing_data': 'empty:'
