config:
    packages:
        -
            name: 'ekyna-cms/editor'
            location: 'bundles/ekynacms/js/editor'
            main: 'editor'
    paths:
        'ekyna-cms/form/tag-choice': 'bundles/ekynacms/js/form/tag-choice'
        'ekyna-cms/cms': 'bundles/ekynacms/js/cms'
build:
    include:
        - 'ekyna-cms/cms'
