config:
    shim:
        backbone:
            deps: ['underscore']
    paths:
        # TODO ekyna-cms/editor package
        'ekyna-cms-editor': 'bundles/ekynacms/js/editor/editor'
        'ekyna-cms-editor/plugin-base': 'bundles/ekynacms/js/editor/plugin/base'
        'ekyna-cms-editor/tinymce': 'bundles/ekynacms/js/editor/plugin/tinymce'
#        'ekyna-cms-editor/image': 'bundles/ekynacms/js/editor/plugin/image'
        'ekyna-cms/cookie': 'bundles/ekynacms/js/cookie'
        'ekyna-cms/user': 'bundles/ekynacms/js/user'
        backbone: 'bundles/ekynacms/lib/backbone'
        underscore: 'bundles/ekynacms/lib/underscore'
build:
    include:
#        - 'ekyna-cms-editor'
#        - 'ekyna-cms-editor/plugin-base'
        - 'ekyna-cms/cookie'
        - 'ekyna-cms/user'
#    paths:
#        'routing_data': 'empty:'
