ekyna_cms_admin:
    resource: "routing/admin.yml"
    prefix:   /admin/content

ekyna_cms_editor:
    resource: "routing/editor.yml"
    prefix:   /cms/editor

ekyna_cms_flashes:
    path: /cms/flashes
    defaults: { _controller: "EkynaCmsBundle:Cms:flashes" }
    methods: [GET]
    options:
        expose: true

ekyna_cms_init:
    path: /cms/init
    defaults: { _controller: "EkynaCmsBundle:Cms:init" }
    methods: [POST]
    options:
        expose: true

ekyna_cms_routing:
    resource: .
    type: cms
