ekyna_cms_file_admin_home:
    path: /
    defaults: { _controller: "ekyna_cms.file.controller:homeAction" }
    requirements:
        _method: GET

ekyna_cms_file_admin_list:
    path: /list
    defaults: { _controller: "ekyna_cms.file.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_cms_file_admin_new:
    path: /new
    defaults: { _controller: "ekyna_cms.file.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_cms_file_admin_show:
    path: /{fileId}/show
    defaults: { _controller: "ekyna_cms.file.controller:showAction" }
    requirements:
        _method: GET
        fileId:  \d+

ekyna_cms_file_admin_edit:
    path: /{fileId}/edit
    defaults: { _controller: "ekyna_cms.file.controller:editAction" }
    requirements:
        _method: GET|POST
        fileId:  \d+

ekyna_cms_file_admin_remove:
    path: /{fileId}/remove
    defaults: { _controller: "ekyna_cms.file.controller:removeAction" }
    requirements:
        _method: GET|POST
        fileId:  \d+
