ekyna_cms_image_admin_home:
    path: /
    defaults: { _controller: "ekyna_cms.image.controller:homeAction" }
    requirements:
        _method: GET

ekyna_cms_image_admin_list:
    path: /list
    defaults: { _controller: "ekyna_cms.image.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_cms_image_admin_new:
    path: /new
    defaults: { _controller: "ekyna_cms.image.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_cms_image_admin_show:
    path: /{imageId}/show
    defaults: { _controller: "ekyna_cms.image.controller:showAction" }
    requirements:
        _method: GET
        imageId:  \d+

ekyna_cms_image_admin_edit:
    path: /{imageId}/edit
    defaults: { _controller: "ekyna_cms.image.controller:editAction" }
    requirements:
        _method: GET|POST
        imageId:  \d+

ekyna_cms_image_admin_remove:
    path: /{imageId}/remove
    defaults: { _controller: "ekyna_cms.image.controller:removeAction" }
    requirements:
        _method: GET|POST
        imageId:  \d+
