ekyna_cms_menu_admin_home:
    path: ""
    controller: "ekyna_cms.menu.controller:homeAction"
    methods: [GET]

ekyna_cms_menu_admin_list:
    path: /list
    controller: "ekyna_cms.menu.controller:listAction"
    methods: [GET, POST]

ekyna_cms_menu_admin_new:
    path: /new
    controller: "ekyna_cms.menu.controller:newAction"
    methods: [GET, POST]

ekyna_cms_menu_admin_new_child:
    path: /{menuId}/new-child
    controller: "ekyna_cms.menu.controller:newChildAction"
    methods: [GET, POST]
    requirements:
        menuId:  \d+

ekyna_cms_menu_admin_show:
    path: /{menuId}/show
    controller: "ekyna_cms.menu.controller:showAction"
    methods: [GET]
    requirements:
        menuId:  \d+

ekyna_cms_menu_admin_edit:
    path: /{menuId}/edit
    controller: "ekyna_cms.menu.controller:editAction"
    methods: [GET, POST]
    requirements:
        menuId:  \d+

ekyna_cms_menu_admin_move_up:
    path: /{menuId}/moveup
    controller: "ekyna_cms.menu.controller:moveUpAction"
    methods: [GET]
    requirements:
        menuId:  \d+

ekyna_cms_menu_admin_move_down:
    path: /{menuId}/movedown
    controller: "ekyna_cms.menu.controller:moveDownAction"
    methods: [GET]
    requirements:
        menuId:  \d+

ekyna_cms_menu_admin_toggle:
    path: /{menuId}/toggle/{field}
    controller: "ekyna_cms.menu.controller:toggleAction"
    methods: [GET]
    defaults: { field: "enabled" }
    requirements:
        menuId:  \d+
        field:  \w+

ekyna_cms_menu_admin_remove:
    path: /{menuId}/remove
    controller: "ekyna_cms.menu.controller:removeAction"
    methods: [GET, POST]
    requirements:
        menuId:  \d+
