ekyna_cms_notice_admin_home:
    path: ""
    controller: "ekyna_cms.notice.controller:homeAction"
    methods: [GET]

ekyna_cms_notice_admin_list:
    path: /list
    controller: "ekyna_cms.notice.controller:listAction"
    methods: [GET, POST]

ekyna_cms_notice_admin_new:
    path: /new
    controller: "ekyna_cms.notice.controller:newAction"
    methods: [GET, POST]

ekyna_cms_notice_admin_show:
    path: /{noticeId}/show
    controller: "ekyna_cms.notice.controller:showAction"
    methods: [GET]
    requirements:
        noticeId:  \d+

ekyna_cms_notice_admin_edit:
    path: /{noticeId}/edit
    controller: "ekyna_cms.notice.controller:editAction"
    methods: [GET, POST]
    requirements:
        noticeId:  \d+

ekyna_cms_notice_admin_tinymce:
    path: /{noticeId}/tinymce/{_locale}/{field}
    controller: "ekyna_cms.notice.controller:tinymceAction"
    methods: [GET]
    requirements:
        field: "[a-zA-Z0-9]+"
        noticeId: \d+
    defaults:
        _locale: "%locale%"
        field: content

ekyna_cms_notice_admin_remove:
    path: /{noticeId}/remove
    controller: "ekyna_cms.notice.controller:removeAction"
    methods: [GET, POST]
    requirements:
        noticeId:  \d+
