ekyna_page_admin_home:
    path: /
    defaults: { _controller: "ekyna_page.controller:homeAction" }
    requirements:
        _method: GET

ekyna_page_admin_list:
    path: /list
    defaults: { _controller: "ekyna_page.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_page_admin_new:
    path: /new
    defaults: { _controller: "ekyna_page.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_page_admin_new_child:
    path: /{pageId}/new-child
    defaults: { _controller: "ekyna_page.controller:newChildAction" }
    requirements:
        _method: GET|POST
        pageId:  \d+

ekyna_page_admin_show:
    path: /{pageId}/show
    defaults: { _controller: "ekyna_page.controller:showAction" }
    requirements:
        _method: GET
        pageId:  \d+

ekyna_page_admin_edit:
    path: /{pageId}/edit
    defaults: { _controller: "ekyna_page.controller:editAction" }
    requirements:
        _method: GET|POST
        pageId:  \d+

ekyna_page_admin_content:
    path: /{pageId}/content
    defaults: { _controller: "ekyna_page.controller:contentShowAction" }
    requirements:
        _method: GET
        pageId:  \d+

ekyna_page_admin_content_edit:
    path: /{pageId}/content/edit
    defaults: { _controller: "ekyna_page.controller:contentEditAction" }
    requirements:
        _method: GET|POST
        pageId:  \d+

ekyna_page_admin_move_up:
    path: /{pageId}/moveup
    defaults: { _controller: "ekyna_page.controller:moveUpAction" }
    requirements:
        _method: GET
        pageId:  \d+

ekyna_page_admin_move_down:
    path: /{pageId}/movedown
    defaults: { _controller: "ekyna_page.controller:moveDownAction" }
    requirements:
        _method: GET
        pageId:  \d+

ekyna_page_admin_remove:
    path: /{pageId}/remove
    defaults: { _controller: "ekyna_page.controller:removeAction" }
    requirements:
        _method: GET|POST
        pageId:  \d+
