ekyna_cms_page_admin_home:
    path: ""
    controller: "ekyna_cms.page.controller:homeAction"
    methods: [GET]

ekyna_cms_page_admin_list:
    path: /list
    controller: "ekyna_cms.page.controller:listAction"
    methods: [GET, POST]

ekyna_cms_page_admin_new:
    path: /new
    controller: "ekyna_cms.page.controller:newAction"
    methods: [GET, POST]

ekyna_cms_page_admin_new_child:
    path: /{pageId}/new-child
    controller: "ekyna_cms.page.controller:newChildAction"
    methods: [GET, POST]
    requirements:
        pageId: \d+
    options:
        expose: true

ekyna_cms_page_admin_show:
    path: /{pageId}/show
    controller: "ekyna_cms.page.controller:showAction"
    methods: [GET]
    requirements:
        pageId: \d+

ekyna_cms_page_admin_edit:
    path: /{pageId}/edit
    controller: "ekyna_cms.page.controller:editAction"
    methods: [GET, POST]
    requirements:
        pageId: \d+
    options:
        expose: true

ekyna_cms_page_admin_tinymce:
    path: /{pageId}/tinymce/{_locale}/{field}
    controller: "ekyna_cms.page.controller:tinymceAction"
    methods: [GET]
    requirements:
        field: "[a-zA-Z0-9]+"
        pageId: \d+
    defaults:
        _locale: "%locale%"
        field: html

ekyna_cms_page_admin_move_up:
    path: /{pageId}/moveup
    controller: "ekyna_cms.page.controller:moveUpAction"
    methods: [GET]
    requirements:
        pageId: \d+

ekyna_cms_page_admin_move_down:
    path: /{pageId}/movedown
    controller: "ekyna_cms.page.controller:moveDownAction"
    methods: [GET]
    requirements:
        pageId: \d+

ekyna_cms_page_admin_toggle:
    path: /{pageId}/toggle/{field}
    controller: "ekyna_cms.page.controller:toggleAction"
    defaults: { field: "enabled" }
    methods: [GET]
    requirements:
        pageId: \d+
        field: \w+

ekyna_cms_page_admin_remove:
    path: /{pageId}/remove
    controller: "ekyna_cms.page.controller:removeAction"
    methods: [GET, POST]
    requirements:
        pageId: \d+
