ekyna_cms_slide_admin_new:
    path: /new
    defaults: { _controller: "ekyna_cms.slide.controller:newAction" }
    methods: [GET|POST]
    requirements:
        slideShowId:  \d+

ekyna_cms_slide_admin_show:
    path: /{slideId}/show
    defaults: { _controller: "ekyna_cms.slide.controller:showAction" }
    methods: [GET]
    requirements:
        slideShowId:  \d+
        slideId:  \d+

ekyna_cms_slide_admin_edit:
    path: /{slideId}/edit
    defaults: { _controller: "ekyna_cms.slide.controller:editAction" }
    methods: [GET|POST]
    requirements:
        slideShowId:  \d+
        slideId:  \d+

ekyna_cms_slide_admin_move_up:
    path: /{slideId}/move-up
    defaults: { _controller: "ekyna_cms.slide.controller:moveUpAction" }
    methods: [GET]
    requirements:
        slideShowId:  \d+
        slideId:  \d+

ekyna_cms_slide_admin_move_down:
    path: /{slideId}/move-down
    defaults: { _controller: "ekyna_cms.slide.controller:moveDownAction" }
    methods: [GET]
    requirements:
        slideShowId:  \d+
        slideId:  \d+

ekyna_cms_slide_admin_remove:
    path: /{slideId}/remove
    defaults: { _controller: "ekyna_cms.slide.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        slideShowId:  \d+
        slideId:  \d+
