ekyna_cms_tag_admin_home:
    path: ""
    defaults: { _controller: "ekyna_cms.tag.controller:homeAction" }
    methods: [GET]

ekyna_cms_tag_admin_list:
    path: /list
    defaults: { _controller: "ekyna_cms.tag.controller:listAction" }
    methods: [GET|POST]

ekyna_cms_tag_admin_new:
    path: /new
    defaults: { _controller: "ekyna_cms.tag.controller:newAction" }
    methods: [GET|POST]

ekyna_cms_tag_admin_show:
    path: /{tagId}/show
    defaults: { _controller: "ekyna_cms.tag.controller:showAction" }
    methods: [GET]
    requirements:
        tagId:  \d+

ekyna_cms_tag_admin_edit:
    path: /{tagId}/edit
    defaults: { _controller: "ekyna_cms.tag.controller:editAction" }
    methods: [GET|POST]
    requirements:
        tagId:  \d+

ekyna_cms_tag_admin_remove:
    path: /{tagId}/remove
    defaults: { _controller: "ekyna_cms.tag.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        tagId:  \d+
