admin_ekyna_cms_editor_container_create_row:
    path: /{containerId}/create-row
    controller: ekyna_cms.controller.editor.container:createRow
    methods: [POST]
    requirements:
        containerId: \d+
    options:
        expose: true

admin_ekyna_cms_editor_container_edit:
    path: /{containerId}/edit
    controller: ekyna_cms.controller.editor.container:edit
    methods: [GET|POST]
    requirements:
        containerId: \d+
    options:
        expose: true

admin_ekyna_cms_editor_container_layout:
    path: /{containerId}/layout
    controller: ekyna_cms.controller.editor.container:layout
    methods: [POST]
    requirements:
        containerId: \d+
    options:
        expose: true

admin_ekyna_cms_editor_container_change_type:
    path: /{containerId}/change-type
    controller: ekyna_cms.controller.editor.container:changeType
    methods: [POST]
    requirements:
        containerId: \d+
    options:
        expose: true

admin_ekyna_cms_editor_container_remove:
    path: /{containerId}/remove
    controller: ekyna_cms.controller.editor.container:remove
    methods: [POST]
    requirements:
        containerId: \d+
    options:
        expose: true

admin_ekyna_cms_editor_container_move_up:
    path: /{containerId}/move-up
    controller: ekyna_cms.controller.editor.container:moveUp
    methods: [POST]
    requirements:
        containerId: \d+
    options:
        expose: true

admin_ekyna_cms_editor_container_move_down:
    path: /{containerId}/move-down
    controller: ekyna_cms.controller.editor.container:moveDown
    methods: [POST]
    requirements:
        containerId: \d+
    options:
        expose: true
