ekyna_cms_editor_row_create_block:
    path: /{rowId}/create-block
    defaults: { _controller: "EkynaCmsBundle:Editor/Row:createBlock" }
    methods: [POST]
    requirements:
        rowId: \d+
    options:
        expose: true

ekyna_cms_editor_row_remove:
    path: /{rowId}/remove
    defaults: { _controller: "EkynaCmsBundle:Editor/Row:remove" }
    methods: [POST]
    requirements:
        rowId: \d+
    options:
        expose: true

ekyna_cms_editor_row_move_up:
    path: /{rowId}/move-up
    defaults: { _controller: "EkynaCmsBundle:Editor/Row:moveUp" }
    methods: [POST]
    requirements:
        rowId: \d+
    options:
        expose: true

ekyna_cms_editor_row_move_down:
    path: /{rowId}/move-down
    defaults: { _controller: "EkynaCmsBundle:Editor/Row:moveDown" }
    methods: [POST]
    requirements:
        rowId: \d+
    options:
        expose: true
