Ekyna\Bundle\CmsBundle\Editor\View\BlockView:
    attributes:
        attributes:
            groups: [Layout, Default]
        pluginAttributes:
            groups: [Content, Default]
        content:
            groups: [Content, Default]
