Ekyna\Bundle\CmsBundle\Editor\View\ContainerView:
    attributes:
        attributes:
            groups: [Layout, Content, Default]
        innerAttributes:
            groups: [Content, Default]
        rows:
            groups: [Layout, Default]
        content:
            groups: [Content, Default]
        innerContent:
            groups: [Content, Default]
