Ekyna\Bundle\CmsBundle\Entity\Page:
    attributes:
        id:
            groups: [Default, Search]
        title:
            groups: [Default, Search]
        html:
            groups: [Default, Search]
#        translations:
#            groups: [Default, Search]
        seo:
            groups: [Default, Search]
#        content:
#            groups: [Default]

#Ekyna\Bundle\CmsBundle\Entity\PageTranslation:
#    attributes:
#        locale:
#            groups: [Default, Search]
#        title:
#            groups: [Default, Search]
#        html:
#            groups: [Default, Search]
