Ekyna\Bundle\CmsBundle\Entity\Page:
    attributes:
        id:
            groups: [Default, Search]
#        content:
#            groups: [Default]
        seo:
            groups: [Default, Search]
