ekyna_admin:
    menus:
        content:
            label: ekyna_core.field.content
            icon: paragraph
            position: 20
            entries:
                pages:
                    route: ekyna_cms_page_admin_list
                    label: ekyna_cms.page.label.plural
                    resource: ekyna_cms_page
                    position: 1
                menus:
                    route: ekyna_cms_menu_admin_list
                    label: ekyna_cms.menu.label.plural
                    resource: ekyna_cms_menu
                    position: 90
                slideShows:
                    route: ekyna_cms_slide_show_admin_list
                    label: ekyna_cms.slide_show.label.plural
                    resource: ekyna_cms_slide_show
                    position: 91
                tags:
                    route: ekyna_cms_tag_admin_list
                    label: ekyna_cms.tag.label.plural
                    resource: ekyna_cms_tag
                    position: 92
                notices:
                    route: ekyna_cms_notice_admin_list
                    label: ekyna_cms.notice.label.plural
                    resource: ekyna_cms_notice
                    position: 93
    navbar:
        buttons:
            cms_editor:
                title: ekyna_cms.editor.title
                route: ekyna_cms_editor_index
                icon: pencil
                target: _blank
                position: 99
            cms_front:
                title: ekyna_admin.navbar.go_to_front
                route: "%ekyna_cms.home_route%"
                icon: sitemap
                target: _blank
                position: 100
    show:
        templates:
            - '@EkynaCms/Show/show_div_layout.html.twig'
