fos_elastica:
    indexes:
        ekyna_cms_page:
            index_name: "%elasticsearch.name%_cms_page"
            types:
                doc:
                    serializer: { groups: [Search] }
                    indexable_callback: isIndexable
                    persistence:
                        driver: orm
                        model: "%ekyna_cms.page.class%"
                        provider:
                            batch_size: 20
                        listener: ~
                        finder: ~
