# Liip Imagine
liip_imagine:
    filter_sets:
        cms_container_background:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                relative_resize: { widen: 1920 }
            post_processors:
                jpegoptim: {}
        cms_block_image:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                relative_resize: { widen: 1140 }
            post_processors:
                jpegoptim: {}
        cms_block_feature:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [600, 600], mode: outbound }
            post_processors:
                jpegoptim: {}
        cms_slideshow_hero:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                relative_resize: { widen: 570 }
            post_processors:
                jpegoptim: {}
