Ekyna\Bundle\CmsBundle\Editor\View\ContentView:
    exclusion_policy: ALL
    properties:
        attributes:
            expose: true
            groups: [Layout, Default]
        containers:
            expose: true
            groups: [Layout, Default]
