Ekyna\Bundle\CmsBundle\Editor\View\RowView:
    exclusion_policy: ALL
    properties:
        attributes:
            expose: true
            groups: [Layout, Default]
        blocks:
            expose: true
            groups: [Layout, Default]
