Ekyna\Bundle\CmsBundle\Entity\Content:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
#        blocks:
#            expose: true
#    virtual_properties:
#        getIndexableContents:
#            expose: true
#            serialized_name: contents
