Ekyna\Bundle\CmsBundle\Entity\Seo:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [Search, Default]
    virtual_properties:
        __toString:
            expose: true
            serialized_name: text
            type: string
            groups: [Search]
