ekyna_cms_page_admin:
    resource: "admin/page.yml"
    prefix:   /pages

ekyna_cms_menu_admin:
    resource: "admin/menu.yml"
    prefix:   /menus

ekyna_cms_notice_admin:
    resource: "admin/notice.yml"
    prefix:   /notices

ekyna_cms_tag_admin:
    resource: "admin/tag.yml"
    prefix:   /tags

ekyna_cms_slide_show_admin:
    resource: "admin/slide_show.yml"
    prefix:   /slide-shows
