# Creates a new {type} block
ekyna_cms_editor_request:
    path: /request
    defaults: { _controller: "EkynaCmsBundle:Editor:request" }
    requirements:
        _method: POST
    options:
        expose: true
        