ekyna_cms_editor_index:
    path: ""
    defaults: { _controller: "EkynaCmsBundle:Editor/Editor:index" }
    methods: [GET]
    options:
        expose: true

ekyna_cms_editor_pages_list:
    path: /pages-list
    defaults: { _controller: "EkynaCmsBundle:Editor/Editor:pagesList" }
    methods: [GET]
    options:
        expose: true

ekyna_cms_editor_content:
    resource: "editor/content.yml"
    prefix: /content

ekyna_cms_editor_container:
    resource: "editor/container.yml"
    prefix: /container

ekyna_cms_editor_row:
    resource: "editor/row.yml"
    prefix: /row

ekyna_cms_editor_block:
    resource: "editor/block.yml"
    prefix: /block
