ekyna_cms_editor_index:
    path: ""
    defaults: { _controller: "EkynaCmsBundle:Editor:index" }
    methods: [GET]
    options:
        expose: true

ekyna_cms_editor_init:
    path: /init
    defaults: { _controller: "EkynaCmsBundle:Editor:init" }
    methods: [GET]
    options:
        expose: true

ekyna_cms_editor_request:
    path: /request
    defaults: { _controller: "EkynaCmsBundle:Editor:request" }
    methods: [POST]
    options:
        expose: true
